[package]
name = "tek4404"
version = "0.1.0"
authors = ["Seth Morabito <web@loomcom.com>"]
edition = "2018"

[build-dependencies]
cc = "1.0"

[dependencies]
num-traits = "0.2"
num-derive = "0.3"
arraydeque = "0.4.5"
sdl2 = "0.34.3"
tokio = { version = "0.2.22", features = ["full"] }
lazy_static = "1.4.0"
byteorder = "1.3.4"
clap = "3.0.0-beta.1"
strum = "0.19"
strum_macros = "0.19"